### ISSUE TITLE
Hello world test withs fails "A JSON text must at least contain two octets!`"

### ISSUE THREAD

**Issue by tortoise74** [asciidoctor/asciidoctor-confluence#13]
When trying to write a test document I got:

`asciidoctor-confluence --host myhost --spaceKey snadbox --title title --username user --password password ~/test.adoc`

Where test.adoc consists of:
<pre>
=== This is a test

Hello World
</pre>

I got:
`An error occurred, the page has not been created because:
A JSON text must at least contain two octets!`

I also tried to add --verbose to diagnose things and got:
<pre>
/home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/options.rb:77:in `init_options': invalid option: --verbose (OptionParser::InvalidOption)
	from /home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/options.rb:20:in `parse!'
	from /home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/options.rb:89:in `parse!'
	from /home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/lib/asciidoctor/confluence/invoker.rb:17:in `invoke'
	from /home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:6:in `<top (required)>'
	from /home/brucea/bin/asciidoctor-confluence:23:in `load'
	from /home/brucea/bin/asciidoctor-confluence:23:in `<main>'
</pre>

`>ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]`

running on RHEL7 x86_64

`asciidoctor-confluence --help` outputs help for both asciidoctor-confluence and asciidoctor before dying:
<pre>
>asciidoctor-confluence --help

Usage: asciidoctor-confluence --host HOSTNAME --spaceKey SPACEKEY --title TITLE [ASCIIDOCTOR OPTIONS]...  FILE...
        --host HOST                  the hostname of the Confluence instance 
        --spaceKey SPACEKEY          the Confluence space within the page will be created
        --title TITLE                the title of the Confluence page
        --pageid PAGEID              the id of the page to update
        --update                     indicate that the page must be updated instead of created
        --username USERNAME          the username used if credential are need to create the page
        --password PASSWORD          the password used if credential are need to create the page
    -h, --help                       Show the full helper (including Asciidoctor helper)
    -V, --version                    display the version and runtime environment (or -v if no other flags or arguments)

Usage: asciidoctor [OPTION]... FILE...
Translate the AsciiDoc source FILE or FILE(s) into the backend output format (e.g., HTML 5, DocBook 4.5, etc.)
By default, the output is written to a file with the basename of the source file and the appropriate extension.
Example: asciidoctor -b html5 source.asciidoc

    -b, --backend BACKEND            set output format backend: [html5, xhtml5, docbook5, docbook45, manpage] (default: html5)
                                     additional backends are supported via extensions (e.g., pdf, latex)
    -d, --doctype DOCTYPE            document type to use when converting document: [article, book, manpage, inline] (default: article)
    -o, --out-file FILE              output file (default: based on path of input file); use - to output to STDOUT
        --safe                       set safe mode level to safe (default: unsafe)
                                     enables include macros, but restricts access to ancestor paths of source file
                                     provided for compatibility with the asciidoc command
    -S, --safe-mode SAFE_MODE        set safe mode level explicitly: [unsafe, safe, server, secure] (default: unsafe)
                                     disables potentially dangerous macros in source files, such as include::[]
    -s, --no-header-footer           suppress output of header and footer (default: false)
    -n, --section-numbers            auto-number section titles in the HTML backend; disabled by default
    -e, --eruby ERUBY                specify eRuby implementation to use when rendering custom ERB templates: [erb, erubis] (default: erb)
    -C, --compact                    compact the output by removing blank lines. (No longer in use)
    -a, --attribute key[=value]      a document attribute to set in the form of key, key! or key=value pair
                                     unless @ is appended to the value, this attributes takes precedence over attributes
                                     defined in the source document
    -T, --template-dir DIR           a directory containing custom converter templates that override the built-in converter (requires tilt gem)
                                     may be specified multiple times
    -E, --template-engine NAME       template engine to use for the custom converter templates (loads gem on demand)
    -B, --base-dir DIR               base directory containing the document and resources (default: directory of source file)
    -D, --destination-dir DIR        destination output directory (default: directory of source file)
    -I, --load-path DIRECTORY        add a directory to the $LOAD_PATH
                                     may be specified more than once
    -r, --require LIBRARY            require the specified library before executing the processor (using require)
                                     may be specified more than once
    -q, --quiet                      suppress warnings (default: false)
        --trace                      include backtrace information on errors (default: false)
    -v, --verbose                    enable verbose mode (default: false)
    -t, --timings                    enable timings mode (default: false)
    -h, --help                       show this message
    -V, --version                    display the version and runtime environment (or -v if no other flags or arguments)
/home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:7:in `exit': no implicit conversion from nil to integer (TypeError)
	from /home/brucea/.gem/ruby/gems/asciidoctor-confluence-0.0.2/bin/asciidoctor-confluence:7:in `<top (required)>'
	from /home/brucea/bin/asciidoctor-confluence:23:in `load'
	from /home/brucea/bin/asciidoctor-confluence:23:in `<main>'
<pre>

**Comment by matzino** [comment]
+1

**Comment by gregamb** [comment]
+1

**Comment by blackshow** [comment]
me too
